<?php

namespace App\Http\Controllers\user_access;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserAccessControl extends Controller
{
    public function getUserAccessMenus(Request $request)
    {
        $menus = [
            '1' => 'Accumulated benefit strategies',
            '2' => 'Accumulated benfit',
            '3' => 'Audit trail maintenance',
            '4' => 'Benefit codes',
            '5' => 'Benefit derivation exclusion listv',
            '6' => 'benefit exception list',
            '7' => 'Billing codes',
            '8' => 'Billing schedule',
            '9' => 'Card production',
            '10' => 'Cause of loss codes',
            '11' => 'Copay network overrides',
            '12' => 'Copay schedules',
            '13' => 'Copay step schedules',
            '14' => 'Copay strategies',
            '15' => 'Coverage strategies',
            '16' => 'Customer/ client/ group',
            '17' => 'Data migration',
            '18' => 'Decision matrixes',
            '19' => 'Diagnosis codes',
            '20' => 'Display benefits',
            '21' => 'DMRs',
            '22' => 'Drug classification',
            '23' => 'Drug coverage',
            '24' => 'Drug coverage classification',
            '25' => 'Drug database',
            '26' => 'Drug price bases',
            '27' => 'Drug price import',
            '28' => 'Drug pricing',
            '29' => 'DUR customization list',
            '30' => 'DUR intervention List',
            '31' => 'DUR message priorities',
            '32' => 'DUR parameters',
            '33' => 'DUR strategies',
            '34' => 'Eligibility validation list',
            '35' => 'Eligibility validations',
            '36' => 'Fee step schedule',
            '37' => 'Formula maintenance',
            '38' => 'Generic code conversion',
            '39' => 'Generic substitution rules',
            '40' => 'GPI exception',
            '41' => 'GPI exclusion lists',
            '42' => 'Limitations list',
            '43' => 'MAC list',
            '44' => 'Maintenance drug list',
            '45' => 'Major medical maximums',
            '46' => 'Membership',
            '47' => 'Membership notes',
            '48' => 'NDC exceptions',
            '49' => 'NDC exclusion lists',
            '50' => 'NDC rebates',
            '51' => 'NDC/ GPI cross reference',
            '52' => 'Package determination lists',
            '53' => 'Patient information',
            '54' => 'Payment codes',
            '55' => 'Performance statistics',
            '56' => 'Pharmacy contracts',
            '57' => 'Plan associations',
            '58' => 'Plan report',
            '59' => 'Plan specific parameters',
            '60' => 'Plan sponsor',
            '61' => 'Plan validation',
            '62' => 'Plans',
            '63' => 'Pref. prod/maint. drug strat',
            '64' => 'Preferred product list',
            '65' => 'Prescriber networks',
            '66' => 'Prescriber strategies',
            '67' => 'Prescriber templates',
            '68' => 'Prescriber validations',
            '69' => 'Prescribers',
            '70' => 'Price comparisons',
            '71' => 'Price schedule',
            '72' => 'Pricing override by drug lists',
            '73' => 'Pricing strategies',
            '74' => 'Prior authorizations',
            '75' => 'Procedure code lists',
            '76' => 'Procedure codes',
            '77' => 'Procedure cross reference',
            '78' => 'Procedure exception lists',
            '79' => 'ProNETs',
            '80' => 'Prov. type/Proc. association',
            '81' => 'Provider adjustments',
            '82' => 'Provider chains',
            '83' => 'Provider networks',
            '84' => 'Provider payments centers',
            '85' => 'Provider system types',
            '86' => 'Provider type validations',
            '87' => 'Provider types',
            '88' => 'Provider validations',
            '89' => 'Providers',
            '90' => 'Reason codes',
            '91' => 'Reason exception lists',
            '92' => 'RVA list',
            '93' => 'RX history',
            '94' => 'RX history payable amounts',
            '95' => 'Service modifiers',
            '96' => 'Service types',
            '97' => 'Specialty validations',
            '98' => 'Step therapy protocol',
            '99' => 'Sub grouping codes',
            '100' => 'Super benefit exception list',
            '101' => 'Super provider networks',
            '102' => 'Super provider networks',
            '103' => 'System parameters',
            '104' => 'Tax schedules',
            '105' => 'Therapy class exceptions',
            '106' => 'UCFs',
            '107' => 'UCR lists',
            '108' => 'User definition',
            '109' => 'Zip codes',
            '110' => 'Zone and NDC'
        ];
        return $this->respondWithToken($this->token(), '', $menus);
    }
}
