<?php

namespace App\Http\Controllers\user_access;

use App\Http\Controllers\Controller;
use App\Traits\AuditTrait;
use Illuminate\Http\Request;

class UserAccessControl extends Controller
{
    use AuditTrait;
    public function getUserAccessMenus(Request $request)
    {
        $menus = [
            ['72' => 'Accumulated benefit strategies'],
            ['47' => 'Accumulated benfit'],
            ['42' => 'Audit trail maintenance'],
            ['100' => 'Benefit codes'],
            ['111' => 'Benefit derivation exclusion listv'],
            ['110' => 'benefit exception list'],
            ['82' => 'Billing codes'],
            ['22' => 'Billing schedule'],
            ['83' => 'Card production'],
            ['104' => 'Cause of loss codes'],
            ['45' => 'Copay network overrides'],
            ['14' => 'Copay schedules'],
            ['17' => 'Copay step schedules'],
            ['71' => 'Copay strategies'],
            ['68' => 'Coverage strategies'],
            ['12' => 'Customer/ client/ group'],
            ['54' => 'Data migration'],
            ['53' => 'Decision matrixes'],
            ['102' => 'Diagnosis codes'],
            ['80' => 'Display benefits'],
            ['11' => 'DMRs'],
            ['4' => 'Drug classification'],
            ['67' => 'Drug coverage'],
            ['69' => 'Drug coverage classification'],
            ['31' => 'Drug database'],
            ['15' => 'Drug price bases'],
            ['41' => 'Drug price import'],
            ['43' => 'Drug pricing'],
            ['89' => 'DUR customization list'],
            ['56' => 'DUR intervention List'],
            ['36' => 'DUR message priorities'],
            ['34' => 'DUR parameters'],
            ['78' => 'DUR strategies'],
            ['76' => 'Eligibility validation list'],
            ['26' => 'Eligibility validations'],
            ['16' => 'Fee step schedule'],
            ['38' => 'Formula maintenance'],
            ['59' => 'Generic code conversion'],
            ['8' => 'Generic substitution rules'],
            ['6' => 'GPI exception'],
            ['50' => 'GPI exclusion lists'],
            ['90' => 'Limitations list'],
            ['18' => 'MAC list'],
            ['57' => 'Maintenance drug list'],
            ['119' => 'Major medical maximums'],
            ['9' => 'Membership'],
            ['84' => 'Membership notes'],
            ['7' => 'NDC exceptions'],
            ['49' => 'NDC exclusion lists'],
            ['33' => 'NDC rebates'],
            ['32' => 'NDC/ GPI cross reference'],
            ['77' => 'Package determination lists'],
            ['46' => 'Patient information'],
            ['81' => 'Payment codes'],
            ['20' => 'Performance statistics'],
            ['44' => 'Pharmacy contracts'],
            ['2' => 'Plan associations'],
            ['3' => 'Plan report'],
            ['35' => 'Plan specific parameters'],
            ['48' => 'Plan sponsor'],
            ['61' => 'Plan validation'],
            ['1' => 'Plans'],
            ['79' => 'Pref. prod/maint. drug strat'],
            ['55' => 'Preferred product list'],
            ['29' => 'Prescriber networks'],
            ['73' => 'Prescriber strategies'],
            ['58' => 'Prescriber templates'],
            ['24' => 'Prescriber validations'],
            ['27' => 'Prescribers'],
            ['52' => 'Price comparisons'],
            ['13' => 'Price schedule'],
            ['85' => 'Pricing override by drug lists'],
            ['70' => 'Pricing strategies'],
            ['10' => 'Prior authorizations'],
            ['114' => 'Procedure code lists'],
            ['101' => 'Procedure codes'],
            ['118' => 'Procedure cross reference'],
            ['108' => 'Procedure exception lists'],
            ['86' => 'ProNETs'],
            ['112' => 'Prov. type/Proc. association'],
            ['60' => 'Provider adjustments'],
            ['64' => 'Provider chains'],
            ['30' => 'Provider networks'],
            ['65' => 'Provider payments centers'],
            ['62' => 'Provider system types'],
            ['113' => 'Provider type validations'],
            ['107' => 'Provider types'],
            ['23' => 'Provider validations'],
            ['28' => 'Providers'],
            ['103' => 'Reason codes'],
            ['109' => 'Reason exception lists'],
            ['116' => 'RVA list'],
            ['39' => 'RX history'],
            ['87' => 'RX history payable amounts'],
            ['105' => 'Service modifiers'],
            ['106' => 'Service types'],
            ['25' => 'Specialty validations'],
            ['66' => 'Step therapy protocol'],
            ['88' => 'Sub grouping codes'],
            ['115' => 'Super benefit exception list'],
            ['74' => 'Super provider networks'],
            ['75' => 'Super prescriber networks'],
            ['19' => 'System parameters'],
            ['51' => 'Tax schedules'],
            ['5' => 'Therapy class exceptions'],
            ['40' => 'UCFs'],
            ['117' => 'UCR lists'],
            ['21' => 'User definition'],
            ['63' => 'Zip codes'],
            ['37' => 'Zone and NDC'],
            ['91' => ''],
            ['92' => ''],
            ['93' => ''],
            ['94' => ''],
            ['95' => ''],
            ['96' => ''],
            ['97' => ''],
            ['98' => ''],
            ['99' => '']
        ];

        // $menus = [
        //     '72' => 'Accumulated benefit strategies',
        //     '47' => 'Accumulated benfit',
        //     '42' => 'Audit trail maintenance',
        //     '100' => 'Benefit codes',
        // ];
        // dd($menus);
        return $this->respondWithToken($this->token(), '', $menus);
    }
}
